name: Continious Delivery

on:
  push:
    branches:
    - master
    - support/*

defaults: *default-defaults

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-dotnet5
      - *setup-nuget
      - *setup-nuget-cache
      - *restore
      - *build
      - *test
      - *pack
      - *publish-codecov
      - *upload-artifacts
  integration-tests:
    name: Integration Tests
    needs: build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - *checkout
      - *setup-dotnet5
      - *setup-nuget
      - *setup-nuget-cache
      - *run-integration-tests
  publish:
    name: Publish
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - *setup-nuget
      - *setup-nuget-cache
      - *download-artifacts
      - *publish-github
