name: Continious Delivery

on:
  push:
    branches:
    - master
    - support/*

defaults: *default-defaults

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-dotnet5
      - *setup-nuget
      - *setup-nuget-cache
      - *restore
      - *build
      - *test
      - *pack
      - *upload-artifacts
      - *publish-github