name: Release

on:
  push:
    tags:
    - v*

defaults: *default-defaults

jobs:
  build:
    name: 'Build & Release'
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet5
    - *setup-nuget

    - name: Setup MinVer
      run: |
        git fetch --tags --force
        git checkout "${GITHUB_REF#refs/*/}"
        dotnet tool install --global minver-cli --version 2.5.0

    - name: 'Verify Tag'
      run: |
        curl https://github.com/AshleighAdams.gpg | gpg --import
        echo "BDE36CC9850449DD77ED51CFBF8DF4780B7BD0AD:6:" | gpg --import-ownertrust # Ashleigh Adams
        git tag --verify "${GITHUB_REF#refs/*/}"
        [[ "v$(minver --tag-prefix=v)" == "${GITHUB_REF#refs/*/}" ]] # error out if the versions don't match

    - *restore
    - *build
    - *test
    - *pack
    - *upload-artifacts

    - name: 'Create Release'
      run: |
        set -x
        tag="${GITHUB_REF#refs/*/}"
        options=()

        git tag -v --format='%(contents:subject)' "$tag" > msg.txt
        echo >> msg.txt
        git tag -v --format='%(contents:body)' "$tag" >> msg.txt
        options+=("-F" "msg.txt")

        if [[ "$(minver --tag-prefix=v --verbosity=e)" == *"-"* ]]; then
          options+=("--prerelease")
        fi

        IFS=$'\n';
        for asset in $(find ./artifacts -name "*.nupkg"); do
          options+=("-a" "$asset")
        done

        hub release create "${options[@]}" "$tag"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Publish Nuget'
      run: |
        dotnet nuget push 'artifacts/*.nupkg' -k ${NUGETORG_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 1
        dotnet nuget push 'artifacts/*.nupkg' -k ${GITHUB_TOKEN} -s github --skip-duplicate --no-symbols 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGETORG_TOKEN: ${{ secrets.NUGETORG_TOKEN }}
