name: Release

on:
  push:
    tags:
    - v*

defaults: *default-defaults

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet5
    - *setup-nuget
    - *setup-nuget-cache

    - name: Setup MinVer for release
      run: |
        git fetch --tags --force
        git checkout "${GITHUB_REF#refs/*/}"
        dotnet tool install --global minver-cli --version 2.4.0
        curl https://github.com/AshleighAdams.gpg | gpg --import

    - *restore
    - *build
    - *test
    - *pack
    - *upload-artifacts

    - name: Create Release
      run: |
        set -x
        tag="${GITHUB_REF#refs/*/}"
        options=()

        git tag -v --format='%(contents:subject)' "$tag" > msg.txt
        echo >> msg.txt
        git tag -v --format='%(contents:body)' "$tag" >> msg.txt
        options+=("-F" "msg.txt")

        if [[ "$(minver --tag-prefix=v --verbosity=e)" == *"-"* ]]; then
          options+=("--prerelease")
        fi

        IFS=$'\n';
        for asset in $(find ./src -name "*.nupkg"); do
          options+=("-a" "$asset")
        done

        hub release create "${options[@]}" "$tag"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Nuget
      run: |
        dotnet nuget push src/**/*.nupkg -k ${NUGETORG_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 1
        dotnet nuget push src/**/*.nupkg -k ${GITHUB_TOKEN} -s github --skip-duplicate --no-symbols 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGETORG_TOKEN: ${{ secrets.NUGETORG_TOKEN }}
